### ISSUE TITLE
Cannot import name 'ConformalIntervals' from 'statsforecast.utils'

### ISSUE THREAD

**Issue by mapabu** [Nixtla/statsforecast#609]
### What happened + What you expected to happen

Hi all! I am trying to test ComformalIntervals for Statforecast. An import error is jumping for me every time I try to import the following: from statsforecast.utils import ConformalIntervals.

ImportError: cannot import name 'ConformalIntervals' from 'statsforecast.utils' (f:\anaconda3\envs\statforenv\lib\site-packages\statsforecast\utils.py)

Apologies if this question is obvious. I might be missing something.

### Versions / Dependencies

I am working in an environment with Python 3.10.0 and Statforecast 1.5.0.

### Reproduction script

import pandas as pd
import numpy as np

from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA, AutoETS, AutoTheta, AutoCES
from statsforecast.utils import ConformalIntervals

### Issue Severity

None

**Comment by kvnkho** [comment]
This has not been released yet. You can try installing from master though if you want to try it out.
